version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: 'campsites'
      POSTGRES_USER: 'test_user'
      POSTGRES_PASSWORD: 'test_password'
    ports:
      - 5432:5432